### ISSUE TITLE
Running the Getting Started with Temoto

### ISSUE THREAD

**Issue by SouLeo** [UTNuclearRoboticsPublic/temoto2#5]
So, I'm installing temoto2 (again...for like the 3rd time) and something different happened on this machine. When I run 

``
roslaunch temoto_2 dual_temoto.launch
``
``
roslaunch temoto_2 temoto_agent.launch
``

The interactive terminal to type text into doesn't pop up. I'm getting a variety of errors: 

From the dual_temoto.launch terminal:
``
::veikumoto/process_manager/ProcessManager::loadCb ERROR: ROS Package: 'temoto_2' does not contain the requsted launch file 'test_2.launch'.
``
``
::veikumoto/process_manager/ResourceServer::wrappedLoadCallback ERROR FWD: 
``
``
::veikumoto/sensor_manager/ResourceClient::call ERROR FWD: 
``
``
::veikumoto/sensor_manager/ResourceManager::call ERROR FWD: 
``
``
::veikumoto/sensor_manager/SensorManagerServers::startSensorCb ERROR FWD: 
``
``
::veikumoto/sensor_manager/ResourceServer::wrappedLoadCallback ERROR FWD: 
``
``
::veikumoto/context_manager/ResourceClient::call ERROR FWD: 
``
``
::veikumoto/context_manager/ResourceManager::call ERROR FWD: 
``
``
::veikumoto/context_manager/ContextManager::loadSpeechCb ERROR FWD: 
``
``
::veikumoto/context_manager/ResourceServer::wrappedLoadCallback ERROR FWD: 
``

From the temoto_agent.launch terminal:

``
::veikumoto/ta_start_terminal_102/context_manager_interface/ResourceClient::call ERROR FWD: 
``
``
::veikumoto/ta_start_terminal_102/context_manager_interface/ResourceManager::call ERROR FWD: 
``
``
::veikumoto/temoto_agent/ContextManagerInterface::getSpeech ERROR FWD: 
``
``
::veikumoto/temoto_agent/TaskTerminal::startTaskWrapped ERROR FWD: 
``

upon review, it seems like the test_2.launch was deleted as of 585735d411a78fdd093d4082abe94aa5984ea607

I'll likely look into this Wednesday for a bit, but help is appreciated.

**Comment by RValner** [comment]
thanks for the info, addressed this issue in https://github.com/UTNuclearRoboticsPublic/temoto2/commit/bb52f7696a4d605e5832f28eb08fb4e7903a3a4b

Tested and should work, reopen the issue if the problem still persists.

**Comment by SouLeo** [comment]
So, I am able to get farther in the same demo; however, I now get the following errors:

dual_temoto.launch

``
::veikumoto/sensor_manager/TaskManager::connectTaskTree ERROR: Couldn't find a suitable task for action: find
``
``
::veikumoto/sensor_manager/TaskManager::executeSFT ERROR FWD: 
``



temoto_agent.launch

``
::veikumoto/temoto_agent/TaskManager::connectTaskTree ERROR: Couldn't find a suitable task for action: start
``
``
::veikumoto/temoto_agent/TaskManager::executeSFT ERROR FWD: 
``

**Comment by SouLeo** [comment]
I had improperly installed MeTA. The issue is resolved.

However, when I do run the program there still is an error:

``
robemoto/context_manager/TaskDescriptorProcessor::getSubject ERROR: Missing 'word' attribute in: /home/<username>/temoto2_ws/src/temoto2/temoto_2/../temoto_actions/object_tracker_actions/ai_track_hand/descriptor.xml
``

But this doesn't otherwise affect my ability to type in commands.

**Comment by RValner** [comment]
The latter is expected because I haven't updated the object tracker actions to newer format
